name: Generate Snake Game

on:
  schedule:
    # Runs every 12 hours
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake Animation and Deploy
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository content
      - name: Checkout repository
        uses: actions/checkout@v3

      # Snake Animation - Output as SVG
      - name: Generate Snake SVG
        uses: Platane/snk@v2
        with:
          github_user_name: Ashishjairamm
          svg_out_path: dist/github-contribution-grid-snake.svg
          snake_color: 'blue'

      # Convert SVG to GIF using an online tool or command line tool
      - name: Install ImageMagick for SVG to GIF conversion
        run: sudo apt-get install imagemagick

      - name: Convert SVG to GIF
        run: convert dist/github-contribution-grid-snake.svg dist/github-contribution-grid-snake.gif

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
